### ISSUE TITLE
Multiple hypens in stream names

### ISSUE THREAD

**Issue by dharmaturtle** [jet/FsCodec#57]
Hi! [The code](https://github.com/jet/FsCodec/blob/master/src/FsCodec/StreamName.fs) currently requires exactly one hyphen in a stream name. Is it reasonable to loosen that restriction? This would permit representing UUIDs in the canonical RFC-4122 format. 

The [readme](https://github.com/jet/FsCodec#stream-naming-conventions) implies this convention is from EventStore. Their category projections allow for some customizations, but notably do not require exactly one hyphen. In fact, when specifying the delimiting character, one must also specify whether to consider the `first` or `last` occurrence of the delimiter. [Docs](https://developers.eventstore.com/server/20.6/server/projections/system-projections.html#by-category).

Some stream name examples just to demonstrate what it would look like:
`account-40DC8220-D240-4530-847C-9F41E286C0A2`
`account-FDEED87B-A89A-40AC-90B4-E89FEE29454E_1A26E0BA-1826-4504-8183-C5EAD0693DB3`

Of course, conventions being conventions, all this may be ineligible for change.

**Comment by bartelink** [comment]
For me, the default config of EventStore (be that first or last hyphen) should win, if >1 is to be permitted (even if these things are configurable).

My main intention is to give relatively clear guidance as to a sensible convention, more than it is to enforce it (always have a category name, use a different separator to split inside the 'aggregate id' portion of the stream name. The only real constraints are:
- in Propulsion (and probably in Prometheus integrations for Equinox), being able to pull out a category from a streamName matters (and you shoiuld not have to enter into a big configuration exercise)
- in EventStore, you're going to have a hard time in practice if you don't have a hyphen and/or if you don't use the default

There's no real problem with relaxing the restrictions, as long as:
- there are sufficient tests (exactly one dash can be tested by eyeballing it)
- the EventStore default is accepted / the standard (be that last or first dash)
- the docs dont end up having to be as long as the EventStore ones ;)

Also, the message lies about the exact rule: https://github.com/jet/FsCodec/blob/master/src/FsCodec/StreamName.fs#L47 and https://github.com/jet/FsCodec/blob/master/src/FsCodec/StreamName.fs#L56 (the category is the bit before the first dash and >1 is handled/accepted due to the `2` being supplied to `Split`)

**Comment by dharmaturtle** [comment]
I realized the code permits multiple hyphens in streamname _identifiers_, which is all I really care about. I opened up a PR about it, and we can continue this discussion [there](https://github.com/jet/FsCodec/pull/58).
